### ISSUE TITLE
ViewPager2嵌套PagerGridView无法正常滑动

### ISSUE THREAD

**Issue by DanteAndroid** [simplepeng/PagerGridView#1]
禁用ViewPager2的滑动事件可以正常滑动。
麻烦作者抽空处理一下~可以[参考这里](https://medium.com/@nasrabadiam/support-nested-scrollable-elements-inside-viewpager2-59fa34978899)

**Comment by simplepeng** [comment]
@DanteAndroid 已经更新`1.0.3`版本
